### Products - Get All Products
GET http://localhost:4000/api/products/list

### Products - Get All Products
GET http://localhost:4000/api/products/all

### Product - Get Product by ID
GET http://localhost:4000/api/products/90247913-d2f8-4175-ab77-3ea1bdf35750

### Auth - Login
POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "password123"
}

### Auth - Sign Up
POST http://localhost:4000/api/auth/sign-up
Content-Type: application/json

{
  "firstName": "Jane",
  "lastName": "Doe",
  "email": "john.doe@example.com",
  "password": "password123"
}

### User - Get Profile
GET http://localhost:4000/api/user/profile

### Cart - Get Cart Items
GET http://localhost:4000/api/cart
Authorization: Bearer <access_token>

### Cart - Add Item to Cart
POST http://localhost:4000/api/cart/add
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "productId": "f060d91e-f97d-4513-a261-168847607c6b",
  "quantity": 1
}

### Cart - Update Item Quantity (set, not add)
PATCH http://localhost:4000/api/cart/90247913-d2f8-4175-ab77-3ea1bdf35750
Content-Type: application/json
Authorization: Bearer <access_token>

{
  "quantity": 3
}

### Cart - Remove Item
DELETE http://localhost:4000/api/cart/90247913-d2f8-4175-ab77-3ea1bdf35750
Authorization: Bearer <access_token>

###